apiVersion: v1
kind: Service
metadata:
  name: customer-query
  namespace: default
  labels:
    app: customer-query
spec:
  type: NodePort
  selector:
    app: customer-query
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
